lib/changkwang_web/router.ex
defmodule ChangkwangWeb.Router do
  use ChangkwangWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admin do
    plug ChangkwangWeb.Plugs.CheckAdmin
  end

  scope "/admin", ChangkwangWeb.Admin do
    pipe_through [:browser, :admin]

    get "/", DashboardController, :index

    resources "/sermons", SermonController
  end

  scope "/", ChangkwangWeb do
    pipe_through :browser

    get "/", HomeController, :index
    get "/intro", IntroController, :index
    get "/servants", ServantsController, :index
    # get "/news", NewsController, :index
    get "/sermons", SermonsController, :index

    get "/login", LoginController, :index
    post "/login", LoginController, :login
  end

  # Other scopes may use custom stacks.
  # scope "/api", ChangkwangWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ChangkwangWeb.Telemetry
    end
  end
end

lib/changkwang_web/views/layout_view.ex
defmodule ChangkwangWeb.LayoutView do
  use ChangkwangWeb, :view
end

lib/changkwang_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Changkwang Church in Atlanta</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
<div class="relative bg-gray-50">
  <div class="relative bg-white shadow">
    <div class="max-w-7xl mx-auto px-4 sm:px-6">
      <div class="flex justify-between items-center py-6 md:justify-start md:space-x-10">
        <div class="w-0 flex-1 flex">
          <a href="<%= Routes.home_path(@conn, :index) %>" class="inline-flex">
            <img class="h-8 w-auto sm:h-10" src="<%= Routes.static_path(@conn, "/images/logo.png") %>" alt="ChangKwang">
            <p class="font-bold text-grey-800 text-3xl ml-5">창광교회</p> 
          </a>
        </div>
        <div class="-mr-2 -my-2 md:hidden">
          <button type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
            <!-- Heroicon name: menu -->
            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
            </svg>
          </button>
        </div>
        <nav class="hidden md:flex space-x-10">
          <a href="<%= Routes.intro_path(@conn, :index) %>" class="text-gray-700 inline-flex items-center space-x-2 text-base leading-6 font-bold hover:text-gray-900 transition ease-in-out duration-150">
            교회 소개
          </a>
          <a href="<%= Routes.servants_path(@conn, :index) %>" class="text-base leading-6 font-bold text-gray-700 hover:text-gray-900 transition ease-in-out duration-150">
            섬기는 분들 
          </a>
          <a href="<%= Routes.sermons_path(@conn, :index) %>" class="text-base leading-6 font-bold text-gray-700 hover:text-gray-900 transition ease-in-out duration-150">
            설교 영상
          </a>
        </nav>
      </div>
    </div>

  </div>
</div>
    <main class="lg:relative container mx-auto">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>