lib/changkwang_web/router.ex
defmodule ChangkwangWeb.Router do
  use ChangkwangWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admin do
    plug ChangkwangWeb.Plugs.CheckAdmin
  end

  scope "/admin", ChangkwangWeb.Admin do
    pipe_through [:browser, :admin]

    get "/", DashboardController, :index

    resources "/sermons", SermonController
  end

  scope "/", ChangkwangWeb do
    pipe_through :browser

    get "/", HomeController, :index
    get "/intro", IntroController, :index
    get "/servants", ServantsController, :index
    # get "/news", NewsController, :index
    get "/sermons", SermonsController, :index

    get "/login", LoginController, :index
    post "/login", LoginController, :login
  end

  # Other scopes may use custom stacks.
  # scope "/api", ChangkwangWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ChangkwangWeb.Telemetry
    end
  end
end

lib/changkwang_web/controllers/login_controller.ex
defmodule ChangkwangWeb.LoginController do
  use ChangkwangWeb, :controller
  alias Changkwang.Accounts

  def index(conn, _params) do
    render(conn, "login.html")
  end

  def login(conn, %{"email" => email, "password" => password} = _params) do
    if user = Accounts.get_user_by_email_and_password(email, password) do
      conn
      |> configure_session(renew: true)
      |> clear_session()
      |> put_session(:user_id, user.id)
      |> redirect(to: Routes.dashboard_path(conn, :index))
    end
  end
end

lib/changkwang_web/views/login_view.ex
defmodule ChangkwangWeb.LoginView do
  use ChangkwangWeb, :view
end

lib/changkwang_web/templates/login/login.html.eex
<div class="min-h-screen bg-gray-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8">

  <div class="sm:mx-auto sm:w-full sm:max-w-md">
    <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
      
      <%= form_for @conn,  Routes.login_path(@conn, :login) ,  fn f -> %>
      <div>
        <label
          for="email"
          class="block text-sm font-medium leading-5 text-gray-700"
        >
          Email address
        </label>

        <div class="mt-1 rounded-md shadow-sm">
          <%= text_input f, :email, id: "email", type: "email", required: true,
          class: "appearance-none block w-full px-3 py-2 border border-gray-300
          rounded-md placeholder-gray-400 focus:outline-none
          focus:shadow-outline-blue focus:border-blue-300 transition
          duration-150 ease-in-out sm:text-sm sm:leading-5" %>
        </div>
      </div>
      <div class="mt-6">
        <label
          for="password"
          class="block text-sm font-medium leading-5 text-gray-700"
        >
          Password
        </label>

        <div class="mt-1 rounded-md shadow-sm">
          <%= text_input f, :password, id: "password", type: "password",
          required: true, class: "appearance-none block w-full px-3 py-2 border
          border-gray-300 rounded-md placeholder-gray-400 focus:outline-none
          focus:shadow-outline-blue focus:border-blue-300 transition
          duration-150 ease-in-out sm:text-sm sm:leading-5" %>
        </div>
        <div class="mt-6">
          <span class="block w-full rounded-md shadow-sm">
            <%= submit "Log in", class: "w-full flex justify-center py-2 px-4
            border border-transparent text-sm font-medium rounded-md text-white
            bg-indigo-600 hover:bg-indigo-500 focus:outline-none
            focus:border-indigo-700 focus:shadow-outline-indigo
            active:bg-indigo-700 transition duration-150 ease-in-out" %>
          </span>
        </div>
      <% end %>
    </div>
  </div>
</div>